name: "Hand Control Pro"
description: "Control Home Assistant using hand gestures via RTSP camera stream."
version: "1.1.6"
slug: "hand_control_pro"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
map:
  - config:rw
options:
  rtsp_url: "rtsp://tfricke:idnfn738%3F22@192.168.178.64:88/videoMain"
  ha_url: "http://192.168.178.164:8123"
  ha_token: ""
  global_cooldown: 5.0
  peace_sign_action: "light.toggle,light.elk_bledom"
  index_pointing_action: ""
  thumbs_up_action: ""
  open_hand_action: ""
  fist_action: ""
  rock_on_action: ""
schema:
  rtsp_url: str
  ha_url: str
  ha_token: str
  global_cooldown: float
  peace_sign_action: str?
  index_pointing_action: str?
  thumbs_up_action: str?
  open_hand_action: str?
  fist_action: str?
  rock_on_action: str?
